"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const multer_1 = __importDefault(require("multer"));
const authMe_1 = require("../controllers/authMe");
const changePassword_1 = require("../controllers/changePassword");
const login_1 = require("../controllers/login");
const product_1 = require("../controllers/product");
const signUp_1 = require("../controllers/signUp");
const upload_1 = require("../controllers/upload");
const auth_1 = require("../middlewares/auth");
const isAdmin_1 = require("../middlewares/isAdmin");
const limitSize_1 = require("../middlewares/limitSize");
const apiRouter = (0, express_1.Router)();
const storage = multer_1.default.memoryStorage();
const multerFilter = (0, multer_1.default)({ storage: storage }).single("image");
apiRouter.use(["/auth/"], auth_1.auth);
apiRouter.post("/login", login_1.loginController);
apiRouter.post("/signup", signUp_1.signUpController);
apiRouter.get("/auth/me", authMe_1.authMeGet);
apiRouter.post("/auth/me", authMe_1.authMePost);
apiRouter.get("/products/:page", product_1.productGet);
apiRouter.get("/products", product_1.productGetPagination);
apiRouter.post("/auth/me/change_password", changePassword_1.changePassword);
apiRouter.post("/auth/products/add", isAdmin_1.isAdmin, product_1.addProductPost);
apiRouter.post("/auth/products/update", isAdmin_1.isAdmin, product_1.updateProductPost);
apiRouter.post("/auth/products/delete", isAdmin_1.isAdmin, product_1.deleteProductPost);
apiRouter.post("/auth/upload/preview/:id", isAdmin_1.isAdmin, multerFilter, limitSize_1.limitSize, upload_1.uploadPreview);
apiRouter.post("/auth/upload/avatar", multerFilter, limitSize_1.limitSize, upload_1.uploadAvatar);
exports.default = apiRouter;
